---
# This playbook contains common plays that will be run on all nodes.

- name: Install requirements
  apt: name={{ item }} state=latest update_cache=yes state=present
  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - postfix

- name: Get rebpository
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash

- name: Install gitlab
  apt: name=gitlab-ce state=latest update_cache=yes state=present

- name: Change gitlab configuration
  template: src=../templates/gitlab.rb.j2 dest=/etc/gitlab/gitlab.rb owner=root group=root mode=600

- name: Create ssl dir
  file: path=/etc/gitlab/ssl state=directory mode=700

- name: Reconfigure Gitlab
  shell: gitlab-ctl reconfigure

- name: Nginx vhost for Gitlab
  template: src=templates/gitlab-http.conf.j2 dest=/etc/nginx/sites-available/gitlab-http.conf owner=root group=root mode=644
  when: embed_nginx == 'false'

- name: Enable vhost
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
      - { src: '/etc/nginx/sites-available/gitlab-http.conf', dest: '/etc/nginx/sites-enabled/gitlab-http.conf' }
  when: embed_nginx == 'false'
...
