---

- name: logstash configuration file
  template:
    src: "../templates/logstash.yml.j2"
    dest: "/etc/logstash/logstash.yml"

- name: logstash configuration file
  template:
    src: "../templates/logstash.conf.j2"
    dest: "/etc/logstash/conf.d/logstash.conf"

- name: logstash configuration file
  service:
    name: "logstash"
    state: restarted
...
