redmine_version: 2.3.1
redmine_directory: /opt/redmine/
redmine_user: redmine
redmine_config_database: |
  production:
    adapter: mysql2
    database: redmine
    host: 192.168.0.105
    username: redmine
    password: redmine
