---

- name: install mysql pip
  become: yes
  apt: name="{{ item }}" state="present" update_cache=yes
  with_items:
    - python-pip
    - python-mysqldb

- name: Set MySQL root password before installing
  become: yes
  debconf: name="mysql-server" question='mysql-server/root_password' value='{{ mysql_root_password | quote}}' vtype='password'

- name: Confirm MySQL root password before installing
  become: yes
  debconf: name="mysql-server" question="mysql-server/root_password_again" value='{{mysql_root_password | quote}}' vtype='password'

- name: Install MySQL
  apt: name={{ item }} state=latest update_cache=yes state=present force=yes
  become: yes
  with_items:
    - mysql-server
    - mysql-client

- name: Create databases user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    priv: '*.*:ALL'
    state: present
  with_items: "{{ mysql_databases }}"

- name: Create databases
  mysql_db: name={{ item.name }} login_user={{ item.user }} login_password={{ item.password | quote}} state=present
  with_items: "{{ mysql_databases }}"

...
